// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PRFileOpener
{
    internal sealed partial class Vsix
    {
        public const string Id = "PRFileOpener.6b8d6338-e27f-471b-be74-c11619f176c9";
        public const string Name = "PR File Opener";
        public const string Description = @"VS Extension to help you do PR reviews easier and faster by opening all added/modified files of current branch in comparison with PRs target branch.";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Ricky Stam";
        public const string Tags = "";
    }
}
